route:
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 24h
  group_by: ['alertname','team','env','location']
  receiver: telegram-default

receivers:
- name: 'telegram-default'
  webhook_configs:
  - send_resolved: true
    url: 'http://tgalert-bot:9087/alert/-IdTgChanel'
